-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE blocks_height_seq;

CREATE SEQUENCE blocks_height_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1
NO CYCLE;

-- Permissions

ALTER SEQUENCE blocks_height_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE blocks_height_seq TO postgres;

-- DROP SEQUENCE restore_histories_id_seq;

CREATE SEQUENCE restore_histories_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1
NO CYCLE;

-- Permissions

ALTER SEQUENCE restore_histories_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE restore_histories_id_seq TO postgres;

-- DROP SEQUENCE transactions_id_seq;

CREATE SEQUENCE transactions_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1
NO CYCLE;

-- Permissions

ALTER SEQUENCE transactions_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE transactions_id_seq TO postgres;

-- DROP SEQUENCE transfers_id_seq;

CREATE SEQUENCE transfers_id_seq
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1
NO CYCLE;

-- Permissions

ALTER SEQUENCE transfers_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE transfers_id_seq TO postgres;
-- public.accounts definition

-- Drop table

-- DROP TABLE accounts;

CREATE TABLE accounts ( address varchar NOT NULL, "token" varchar NOT NULL, amount float8 NOT NULL, CONSTRAINT accounts_pkey null);
CREATE UNIQUE INDEX account_address_token ON accounts (address text_ops,"token" text_ops);

-- Permissions

ALTER TABLE accounts OWNER TO postgres;
GRANT ALL ON TABLE accounts TO postgres;


-- public.blocks definition

-- Drop table

-- DROP TABLE blocks;

CREATE TABLE blocks ( CONSTRAINT blocks_pkey PRIMARY KEY (height));

-- Permissions

ALTER TABLE blocks OWNER TO postgres;
GRANT ALL ON TABLE blocks TO postgres;


-- public.restore_histories definition

-- Drop table

-- DROP TABLE restore_histories;

CREATE TABLE restore_histories ( CONSTRAINT restore_histories_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE restore_histories OWNER TO postgres;
GRANT ALL ON TABLE restore_histories TO postgres;


-- public.transactions definition

-- Drop table

-- DROP TABLE transactions;

CREATE TABLE transactions ( CONSTRAINT transactions_pkey PRIMARY KEY (id));

-- Permissions

ALTER TABLE transactions OWNER TO postgres;
GRANT ALL ON TABLE transactions TO postgres;


-- public.transfers definition

-- Drop table

-- DROP TABLE transfers;

CREATE TABLE transfers ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, hash varchar NOT NULL, func varchar NOT NULL, from_address varchar NULL, to_address varchar NULL, "token" varchar NOT NULL, amount float8 NOT NULL, denom varchar NOT NULL, created_at timestamptz NOT NULL, CONSTRAINT transfers_pkey null, CONSTRAINT transfers_accounts_transfers_from FOREIGN KEY (from_address) REFERENCES accounts(address) ON DELETE SET NULL, CONSTRAINT transfers_accounts_transfers_to FOREIGN KEY (to_address) REFERENCES accounts(address) ON DELETE SET NULL);
CREATE INDEX transfer_from_address_token ON transfers (from_address text_ops,"token" text_ops);
CREATE INDEX transfer_to_address_token ON transfers (to_address text_ops,"token" text_ops);

-- Permissions

ALTER TABLE transfers OWNER TO postgres;
GRANT ALL ON TABLE transfers TO postgres;


-- Permissions;
