// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlocksColumns holds the columns for the "blocks" table.
	BlocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString},
		{Name: "height", Type: field.TypeInt},
		{Name: "time", Type: field.TypeTime},
		{Name: "total_txs", Type: field.TypeInt},
		{Name: "num_txs", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BlocksTable holds the schema information for the "blocks" table.
	BlocksTable = &schema.Table{
		Name:       "blocks",
		Columns:    BlocksColumns,
		PrimaryKey: []*schema.Column{BlocksColumns[0]},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "index", Type: field.TypeInt},
		{Name: "hash", Type: field.TypeString},
		{Name: "success", Type: field.TypeBool, Default: false},
		{Name: "block_height", Type: field.TypeInt},
		{Name: "gas_wanted", Type: field.TypeFloat64},
		{Name: "gas_used", Type: field.TypeFloat64},
		{Name: "memo", Type: field.TypeString, Nullable: true},
		{Name: "gas_fee", Type: field.TypeJSON, Nullable: true},
		{Name: "messages", Type: field.TypeJSON, Nullable: true},
		{Name: "response", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlocksTable,
		TransactionsTable,
	}
)

func init() {
}
