// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gno.land-block-indexer/ent/block"
)

// BlockCreate is the builder for creating a Block entity.
type BlockCreate struct {
	config
	mutation *BlockMutation
	hooks    []Hook
}

// SetHash sets the "hash" field.
func (_c *BlockCreate) SetHash(v string) *BlockCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *BlockCreate) SetHeight(v int) *BlockCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetTime sets the "time" field.
func (_c *BlockCreate) SetTime(v time.Time) *BlockCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetTotalTxs sets the "total_txs" field.
func (_c *BlockCreate) SetTotalTxs(v int) *BlockCreate {
	_c.mutation.SetTotalTxs(v)
	return _c
}

// SetNumTxs sets the "num_txs" field.
func (_c *BlockCreate) SetNumTxs(v int) *BlockCreate {
	_c.mutation.SetNumTxs(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlockCreate) SetCreatedAt(v time.Time) *BlockCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlockCreate) SetNillableCreatedAt(v *time.Time) *BlockCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the BlockMutation object of the builder.
func (_c *BlockCreate) Mutation() *BlockMutation {
	return _c.mutation
}

// Save creates the Block in the database.
func (_c *BlockCreate) Save(ctx context.Context) (*Block, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlockCreate) SaveX(ctx context.Context) *Block {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlockCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlockCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlockCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := block.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlockCreate) check() error {
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Block.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := block.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Block.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Block.height"`)}
	}
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Block.time"`)}
	}
	if _, ok := _c.mutation.TotalTxs(); !ok {
		return &ValidationError{Name: "total_txs", err: errors.New(`ent: missing required field "Block.total_txs"`)}
	}
	if _, ok := _c.mutation.NumTxs(); !ok {
		return &ValidationError{Name: "num_txs", err: errors.New(`ent: missing required field "Block.num_txs"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Block.created_at"`)}
	}
	return nil
}

func (_c *BlockCreate) sqlSave(ctx context.Context) (*Block, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlockCreate) createSpec() (*Block, *sqlgraph.CreateSpec) {
	var (
		_node = &Block{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(block.Table, sqlgraph.NewFieldSpec(block.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(block.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(block.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(block.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if value, ok := _c.mutation.TotalTxs(); ok {
		_spec.SetField(block.FieldTotalTxs, field.TypeInt, value)
		_node.TotalTxs = value
	}
	if value, ok := _c.mutation.NumTxs(); ok {
		_spec.SetField(block.FieldNumTxs, field.TypeInt, value)
		_node.NumTxs = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(block.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// BlockCreateBulk is the builder for creating many Block entities in bulk.
type BlockCreateBulk struct {
	config
	err      error
	builders []*BlockCreate
}

// Save creates the Block entities in the database.
func (_c *BlockCreateBulk) Save(ctx context.Context) ([]*Block, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Block, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlockCreateBulk) SaveX(ctx context.Context) []*Block {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlockCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlockCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
