// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gno.land-block-indexer/ent/block"
	"gno.land-block-indexer/ent/predicate"
	"gno.land-block-indexer/ent/schema"
	"gno.land-block-indexer/ent/transaction"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBlock       = "Block"
	TypeTransaction = "Transaction"
)

// BlockMutation represents an operation that mutates the Block nodes in the graph.
type BlockMutation struct {
	config
	op            Op
	typ           string
	id            *int
	hash          *string
	height        *int
	addheight     *int
	time          *time.Time
	total_txs     *int
	addtotal_txs  *int
	num_txs       *int
	addnum_txs    *int
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Block, error)
	predicates    []predicate.Block
}

var _ ent.Mutation = (*BlockMutation)(nil)

// blockOption allows management of the mutation configuration using functional options.
type blockOption func(*BlockMutation)

// newBlockMutation creates new mutation for the Block entity.
func newBlockMutation(c config, op Op, opts ...blockOption) *BlockMutation {
	m := &BlockMutation{
		config:        c,
		op:            op,
		typ:           TypeBlock,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBlockID sets the ID field of the mutation.
func withBlockID(id int) blockOption {
	return func(m *BlockMutation) {
		var (
			err   error
			once  sync.Once
			value *Block
		)
		m.oldValue = func(ctx context.Context) (*Block, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Block.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBlock sets the old Block of the mutation.
func withBlock(node *Block) blockOption {
	return func(m *BlockMutation) {
		m.oldValue = func(context.Context) (*Block, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BlockMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BlockMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BlockMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BlockMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Block.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHash sets the "hash" field.
func (m *BlockMutation) SetHash(s string) {
	m.hash = &s
}

// Hash returns the value of the "hash" field in the mutation.
func (m *BlockMutation) Hash() (r string, exists bool) {
	v := m.hash
	if v == nil {
		return
	}
	return *v, true
}

// OldHash returns the old "hash" field's value of the Block entity.
// If the Block object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlockMutation) OldHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHash: %w", err)
	}
	return oldValue.Hash, nil
}

// ResetHash resets all changes to the "hash" field.
func (m *BlockMutation) ResetHash() {
	m.hash = nil
}

// SetHeight sets the "height" field.
func (m *BlockMutation) SetHeight(i int) {
	m.height = &i
	m.addheight = nil
}

// Height returns the value of the "height" field in the mutation.
func (m *BlockMutation) Height() (r int, exists bool) {
	v := m.height
	if v == nil {
		return
	}
	return *v, true
}

// OldHeight returns the old "height" field's value of the Block entity.
// If the Block object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlockMutation) OldHeight(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeight: %w", err)
	}
	return oldValue.Height, nil
}

// AddHeight adds i to the "height" field.
func (m *BlockMutation) AddHeight(i int) {
	if m.addheight != nil {
		*m.addheight += i
	} else {
		m.addheight = &i
	}
}

// AddedHeight returns the value that was added to the "height" field in this mutation.
func (m *BlockMutation) AddedHeight() (r int, exists bool) {
	v := m.addheight
	if v == nil {
		return
	}
	return *v, true
}

// ResetHeight resets all changes to the "height" field.
func (m *BlockMutation) ResetHeight() {
	m.height = nil
	m.addheight = nil
}

// SetTime sets the "time" field.
func (m *BlockMutation) SetTime(t time.Time) {
	m.time = &t
}

// Time returns the value of the "time" field in the mutation.
func (m *BlockMutation) Time() (r time.Time, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the Block entity.
// If the Block object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlockMutation) OldTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "time" field.
func (m *BlockMutation) ResetTime() {
	m.time = nil
}

// SetTotalTxs sets the "total_txs" field.
func (m *BlockMutation) SetTotalTxs(i int) {
	m.total_txs = &i
	m.addtotal_txs = nil
}

// TotalTxs returns the value of the "total_txs" field in the mutation.
func (m *BlockMutation) TotalTxs() (r int, exists bool) {
	v := m.total_txs
	if v == nil {
		return
	}
	return *v, true
}

// OldTotalTxs returns the old "total_txs" field's value of the Block entity.
// If the Block object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlockMutation) OldTotalTxs(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTotalTxs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTotalTxs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTotalTxs: %w", err)
	}
	return oldValue.TotalTxs, nil
}

// AddTotalTxs adds i to the "total_txs" field.
func (m *BlockMutation) AddTotalTxs(i int) {
	if m.addtotal_txs != nil {
		*m.addtotal_txs += i
	} else {
		m.addtotal_txs = &i
	}
}

// AddedTotalTxs returns the value that was added to the "total_txs" field in this mutation.
func (m *BlockMutation) AddedTotalTxs() (r int, exists bool) {
	v := m.addtotal_txs
	if v == nil {
		return
	}
	return *v, true
}

// ResetTotalTxs resets all changes to the "total_txs" field.
func (m *BlockMutation) ResetTotalTxs() {
	m.total_txs = nil
	m.addtotal_txs = nil
}

// SetNumTxs sets the "num_txs" field.
func (m *BlockMutation) SetNumTxs(i int) {
	m.num_txs = &i
	m.addnum_txs = nil
}

// NumTxs returns the value of the "num_txs" field in the mutation.
func (m *BlockMutation) NumTxs() (r int, exists bool) {
	v := m.num_txs
	if v == nil {
		return
	}
	return *v, true
}

// OldNumTxs returns the old "num_txs" field's value of the Block entity.
// If the Block object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlockMutation) OldNumTxs(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNumTxs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNumTxs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNumTxs: %w", err)
	}
	return oldValue.NumTxs, nil
}

// AddNumTxs adds i to the "num_txs" field.
func (m *BlockMutation) AddNumTxs(i int) {
	if m.addnum_txs != nil {
		*m.addnum_txs += i
	} else {
		m.addnum_txs = &i
	}
}

// AddedNumTxs returns the value that was added to the "num_txs" field in this mutation.
func (m *BlockMutation) AddedNumTxs() (r int, exists bool) {
	v := m.addnum_txs
	if v == nil {
		return
	}
	return *v, true
}

// ResetNumTxs resets all changes to the "num_txs" field.
func (m *BlockMutation) ResetNumTxs() {
	m.num_txs = nil
	m.addnum_txs = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *BlockMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *BlockMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Block entity.
// If the Block object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BlockMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *BlockMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the BlockMutation builder.
func (m *BlockMutation) Where(ps ...predicate.Block) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the BlockMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *BlockMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Block, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *BlockMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *BlockMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Block).
func (m *BlockMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BlockMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.hash != nil {
		fields = append(fields, block.FieldHash)
	}
	if m.height != nil {
		fields = append(fields, block.FieldHeight)
	}
	if m.time != nil {
		fields = append(fields, block.FieldTime)
	}
	if m.total_txs != nil {
		fields = append(fields, block.FieldTotalTxs)
	}
	if m.num_txs != nil {
		fields = append(fields, block.FieldNumTxs)
	}
	if m.created_at != nil {
		fields = append(fields, block.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BlockMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case block.FieldHash:
		return m.Hash()
	case block.FieldHeight:
		return m.Height()
	case block.FieldTime:
		return m.Time()
	case block.FieldTotalTxs:
		return m.TotalTxs()
	case block.FieldNumTxs:
		return m.NumTxs()
	case block.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BlockMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case block.FieldHash:
		return m.OldHash(ctx)
	case block.FieldHeight:
		return m.OldHeight(ctx)
	case block.FieldTime:
		return m.OldTime(ctx)
	case block.FieldTotalTxs:
		return m.OldTotalTxs(ctx)
	case block.FieldNumTxs:
		return m.OldNumTxs(ctx)
	case block.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Block field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BlockMutation) SetField(name string, value ent.Value) error {
	switch name {
	case block.FieldHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHash(v)
		return nil
	case block.FieldHeight:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeight(v)
		return nil
	case block.FieldTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	case block.FieldTotalTxs:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTotalTxs(v)
		return nil
	case block.FieldNumTxs:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNumTxs(v)
		return nil
	case block.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Block field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BlockMutation) AddedFields() []string {
	var fields []string
	if m.addheight != nil {
		fields = append(fields, block.FieldHeight)
	}
	if m.addtotal_txs != nil {
		fields = append(fields, block.FieldTotalTxs)
	}
	if m.addnum_txs != nil {
		fields = append(fields, block.FieldNumTxs)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BlockMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case block.FieldHeight:
		return m.AddedHeight()
	case block.FieldTotalTxs:
		return m.AddedTotalTxs()
	case block.FieldNumTxs:
		return m.AddedNumTxs()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BlockMutation) AddField(name string, value ent.Value) error {
	switch name {
	case block.FieldHeight:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHeight(v)
		return nil
	case block.FieldTotalTxs:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTotalTxs(v)
		return nil
	case block.FieldNumTxs:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddNumTxs(v)
		return nil
	}
	return fmt.Errorf("unknown Block numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BlockMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BlockMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BlockMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Block nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BlockMutation) ResetField(name string) error {
	switch name {
	case block.FieldHash:
		m.ResetHash()
		return nil
	case block.FieldHeight:
		m.ResetHeight()
		return nil
	case block.FieldTime:
		m.ResetTime()
		return nil
	case block.FieldTotalTxs:
		m.ResetTotalTxs()
		return nil
	case block.FieldNumTxs:
		m.ResetNumTxs()
		return nil
	case block.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Block field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BlockMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BlockMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BlockMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BlockMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BlockMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BlockMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BlockMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Block unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BlockMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Block edge %s", name)
}

// TransactionMutation represents an operation that mutates the Transaction nodes in the graph.
type TransactionMutation struct {
	config
	op              Op
	typ             string
	id              *int
	index           *int
	addindex        *int
	hash            *string
	success         *bool
	block_height    *int
	addblock_height *int
	gas_wanted      *float64
	addgas_wanted   *float64
	gas_used        *float64
	addgas_used     *float64
	memo            *string
	gas_fee         *schema.GasFee
	messages        *[]schema.Message
	appendmessages  []schema.Message
	response        *schema.Response
	created_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Transaction, error)
	predicates      []predicate.Transaction
}

var _ ent.Mutation = (*TransactionMutation)(nil)

// transactionOption allows management of the mutation configuration using functional options.
type transactionOption func(*TransactionMutation)

// newTransactionMutation creates new mutation for the Transaction entity.
func newTransactionMutation(c config, op Op, opts ...transactionOption) *TransactionMutation {
	m := &TransactionMutation{
		config:        c,
		op:            op,
		typ:           TypeTransaction,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTransactionID sets the ID field of the mutation.
func withTransactionID(id int) transactionOption {
	return func(m *TransactionMutation) {
		var (
			err   error
			once  sync.Once
			value *Transaction
		)
		m.oldValue = func(ctx context.Context) (*Transaction, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Transaction.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTransaction sets the old Transaction of the mutation.
func withTransaction(node *Transaction) transactionOption {
	return func(m *TransactionMutation) {
		m.oldValue = func(context.Context) (*Transaction, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TransactionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TransactionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TransactionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TransactionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Transaction.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetIndex sets the "index" field.
func (m *TransactionMutation) SetIndex(i int) {
	m.index = &i
	m.addindex = nil
}

// Index returns the value of the "index" field in the mutation.
func (m *TransactionMutation) Index() (r int, exists bool) {
	v := m.index
	if v == nil {
		return
	}
	return *v, true
}

// OldIndex returns the old "index" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldIndex(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIndex is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIndex requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIndex: %w", err)
	}
	return oldValue.Index, nil
}

// AddIndex adds i to the "index" field.
func (m *TransactionMutation) AddIndex(i int) {
	if m.addindex != nil {
		*m.addindex += i
	} else {
		m.addindex = &i
	}
}

// AddedIndex returns the value that was added to the "index" field in this mutation.
func (m *TransactionMutation) AddedIndex() (r int, exists bool) {
	v := m.addindex
	if v == nil {
		return
	}
	return *v, true
}

// ResetIndex resets all changes to the "index" field.
func (m *TransactionMutation) ResetIndex() {
	m.index = nil
	m.addindex = nil
}

// SetHash sets the "hash" field.
func (m *TransactionMutation) SetHash(s string) {
	m.hash = &s
}

// Hash returns the value of the "hash" field in the mutation.
func (m *TransactionMutation) Hash() (r string, exists bool) {
	v := m.hash
	if v == nil {
		return
	}
	return *v, true
}

// OldHash returns the old "hash" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldHash(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHash is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHash requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHash: %w", err)
	}
	return oldValue.Hash, nil
}

// ResetHash resets all changes to the "hash" field.
func (m *TransactionMutation) ResetHash() {
	m.hash = nil
}

// SetSuccess sets the "success" field.
func (m *TransactionMutation) SetSuccess(b bool) {
	m.success = &b
}

// Success returns the value of the "success" field in the mutation.
func (m *TransactionMutation) Success() (r bool, exists bool) {
	v := m.success
	if v == nil {
		return
	}
	return *v, true
}

// OldSuccess returns the old "success" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldSuccess(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSuccess is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSuccess requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSuccess: %w", err)
	}
	return oldValue.Success, nil
}

// ResetSuccess resets all changes to the "success" field.
func (m *TransactionMutation) ResetSuccess() {
	m.success = nil
}

// SetBlockHeight sets the "block_height" field.
func (m *TransactionMutation) SetBlockHeight(i int) {
	m.block_height = &i
	m.addblock_height = nil
}

// BlockHeight returns the value of the "block_height" field in the mutation.
func (m *TransactionMutation) BlockHeight() (r int, exists bool) {
	v := m.block_height
	if v == nil {
		return
	}
	return *v, true
}

// OldBlockHeight returns the old "block_height" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldBlockHeight(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBlockHeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBlockHeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBlockHeight: %w", err)
	}
	return oldValue.BlockHeight, nil
}

// AddBlockHeight adds i to the "block_height" field.
func (m *TransactionMutation) AddBlockHeight(i int) {
	if m.addblock_height != nil {
		*m.addblock_height += i
	} else {
		m.addblock_height = &i
	}
}

// AddedBlockHeight returns the value that was added to the "block_height" field in this mutation.
func (m *TransactionMutation) AddedBlockHeight() (r int, exists bool) {
	v := m.addblock_height
	if v == nil {
		return
	}
	return *v, true
}

// ResetBlockHeight resets all changes to the "block_height" field.
func (m *TransactionMutation) ResetBlockHeight() {
	m.block_height = nil
	m.addblock_height = nil
}

// SetGasWanted sets the "gas_wanted" field.
func (m *TransactionMutation) SetGasWanted(f float64) {
	m.gas_wanted = &f
	m.addgas_wanted = nil
}

// GasWanted returns the value of the "gas_wanted" field in the mutation.
func (m *TransactionMutation) GasWanted() (r float64, exists bool) {
	v := m.gas_wanted
	if v == nil {
		return
	}
	return *v, true
}

// OldGasWanted returns the old "gas_wanted" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldGasWanted(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGasWanted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGasWanted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGasWanted: %w", err)
	}
	return oldValue.GasWanted, nil
}

// AddGasWanted adds f to the "gas_wanted" field.
func (m *TransactionMutation) AddGasWanted(f float64) {
	if m.addgas_wanted != nil {
		*m.addgas_wanted += f
	} else {
		m.addgas_wanted = &f
	}
}

// AddedGasWanted returns the value that was added to the "gas_wanted" field in this mutation.
func (m *TransactionMutation) AddedGasWanted() (r float64, exists bool) {
	v := m.addgas_wanted
	if v == nil {
		return
	}
	return *v, true
}

// ResetGasWanted resets all changes to the "gas_wanted" field.
func (m *TransactionMutation) ResetGasWanted() {
	m.gas_wanted = nil
	m.addgas_wanted = nil
}

// SetGasUsed sets the "gas_used" field.
func (m *TransactionMutation) SetGasUsed(f float64) {
	m.gas_used = &f
	m.addgas_used = nil
}

// GasUsed returns the value of the "gas_used" field in the mutation.
func (m *TransactionMutation) GasUsed() (r float64, exists bool) {
	v := m.gas_used
	if v == nil {
		return
	}
	return *v, true
}

// OldGasUsed returns the old "gas_used" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldGasUsed(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGasUsed is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGasUsed requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGasUsed: %w", err)
	}
	return oldValue.GasUsed, nil
}

// AddGasUsed adds f to the "gas_used" field.
func (m *TransactionMutation) AddGasUsed(f float64) {
	if m.addgas_used != nil {
		*m.addgas_used += f
	} else {
		m.addgas_used = &f
	}
}

// AddedGasUsed returns the value that was added to the "gas_used" field in this mutation.
func (m *TransactionMutation) AddedGasUsed() (r float64, exists bool) {
	v := m.addgas_used
	if v == nil {
		return
	}
	return *v, true
}

// ResetGasUsed resets all changes to the "gas_used" field.
func (m *TransactionMutation) ResetGasUsed() {
	m.gas_used = nil
	m.addgas_used = nil
}

// SetMemo sets the "memo" field.
func (m *TransactionMutation) SetMemo(s string) {
	m.memo = &s
}

// Memo returns the value of the "memo" field in the mutation.
func (m *TransactionMutation) Memo() (r string, exists bool) {
	v := m.memo
	if v == nil {
		return
	}
	return *v, true
}

// OldMemo returns the old "memo" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldMemo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMemo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMemo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMemo: %w", err)
	}
	return oldValue.Memo, nil
}

// ClearMemo clears the value of the "memo" field.
func (m *TransactionMutation) ClearMemo() {
	m.memo = nil
	m.clearedFields[transaction.FieldMemo] = struct{}{}
}

// MemoCleared returns if the "memo" field was cleared in this mutation.
func (m *TransactionMutation) MemoCleared() bool {
	_, ok := m.clearedFields[transaction.FieldMemo]
	return ok
}

// ResetMemo resets all changes to the "memo" field.
func (m *TransactionMutation) ResetMemo() {
	m.memo = nil
	delete(m.clearedFields, transaction.FieldMemo)
}

// SetGasFee sets the "gas_fee" field.
func (m *TransactionMutation) SetGasFee(sf schema.GasFee) {
	m.gas_fee = &sf
}

// GasFee returns the value of the "gas_fee" field in the mutation.
func (m *TransactionMutation) GasFee() (r schema.GasFee, exists bool) {
	v := m.gas_fee
	if v == nil {
		return
	}
	return *v, true
}

// OldGasFee returns the old "gas_fee" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldGasFee(ctx context.Context) (v schema.GasFee, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGasFee is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGasFee requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGasFee: %w", err)
	}
	return oldValue.GasFee, nil
}

// ClearGasFee clears the value of the "gas_fee" field.
func (m *TransactionMutation) ClearGasFee() {
	m.gas_fee = nil
	m.clearedFields[transaction.FieldGasFee] = struct{}{}
}

// GasFeeCleared returns if the "gas_fee" field was cleared in this mutation.
func (m *TransactionMutation) GasFeeCleared() bool {
	_, ok := m.clearedFields[transaction.FieldGasFee]
	return ok
}

// ResetGasFee resets all changes to the "gas_fee" field.
func (m *TransactionMutation) ResetGasFee() {
	m.gas_fee = nil
	delete(m.clearedFields, transaction.FieldGasFee)
}

// SetMessages sets the "messages" field.
func (m *TransactionMutation) SetMessages(s []schema.Message) {
	m.messages = &s
	m.appendmessages = nil
}

// Messages returns the value of the "messages" field in the mutation.
func (m *TransactionMutation) Messages() (r []schema.Message, exists bool) {
	v := m.messages
	if v == nil {
		return
	}
	return *v, true
}

// OldMessages returns the old "messages" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldMessages(ctx context.Context) (v []schema.Message, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMessages is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMessages requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMessages: %w", err)
	}
	return oldValue.Messages, nil
}

// AppendMessages adds s to the "messages" field.
func (m *TransactionMutation) AppendMessages(s []schema.Message) {
	m.appendmessages = append(m.appendmessages, s...)
}

// AppendedMessages returns the list of values that were appended to the "messages" field in this mutation.
func (m *TransactionMutation) AppendedMessages() ([]schema.Message, bool) {
	if len(m.appendmessages) == 0 {
		return nil, false
	}
	return m.appendmessages, true
}

// ClearMessages clears the value of the "messages" field.
func (m *TransactionMutation) ClearMessages() {
	m.messages = nil
	m.appendmessages = nil
	m.clearedFields[transaction.FieldMessages] = struct{}{}
}

// MessagesCleared returns if the "messages" field was cleared in this mutation.
func (m *TransactionMutation) MessagesCleared() bool {
	_, ok := m.clearedFields[transaction.FieldMessages]
	return ok
}

// ResetMessages resets all changes to the "messages" field.
func (m *TransactionMutation) ResetMessages() {
	m.messages = nil
	m.appendmessages = nil
	delete(m.clearedFields, transaction.FieldMessages)
}

// SetResponse sets the "response" field.
func (m *TransactionMutation) SetResponse(s schema.Response) {
	m.response = &s
}

// Response returns the value of the "response" field in the mutation.
func (m *TransactionMutation) Response() (r schema.Response, exists bool) {
	v := m.response
	if v == nil {
		return
	}
	return *v, true
}

// OldResponse returns the old "response" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldResponse(ctx context.Context) (v schema.Response, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponse is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponse requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponse: %w", err)
	}
	return oldValue.Response, nil
}

// ClearResponse clears the value of the "response" field.
func (m *TransactionMutation) ClearResponse() {
	m.response = nil
	m.clearedFields[transaction.FieldResponse] = struct{}{}
}

// ResponseCleared returns if the "response" field was cleared in this mutation.
func (m *TransactionMutation) ResponseCleared() bool {
	_, ok := m.clearedFields[transaction.FieldResponse]
	return ok
}

// ResetResponse resets all changes to the "response" field.
func (m *TransactionMutation) ResetResponse() {
	m.response = nil
	delete(m.clearedFields, transaction.FieldResponse)
}

// SetCreatedAt sets the "created_at" field.
func (m *TransactionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TransactionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Transaction entity.
// If the Transaction object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TransactionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TransactionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the TransactionMutation builder.
func (m *TransactionMutation) Where(ps ...predicate.Transaction) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the TransactionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *TransactionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Transaction, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *TransactionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TransactionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Transaction).
func (m *TransactionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TransactionMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.index != nil {
		fields = append(fields, transaction.FieldIndex)
	}
	if m.hash != nil {
		fields = append(fields, transaction.FieldHash)
	}
	if m.success != nil {
		fields = append(fields, transaction.FieldSuccess)
	}
	if m.block_height != nil {
		fields = append(fields, transaction.FieldBlockHeight)
	}
	if m.gas_wanted != nil {
		fields = append(fields, transaction.FieldGasWanted)
	}
	if m.gas_used != nil {
		fields = append(fields, transaction.FieldGasUsed)
	}
	if m.memo != nil {
		fields = append(fields, transaction.FieldMemo)
	}
	if m.gas_fee != nil {
		fields = append(fields, transaction.FieldGasFee)
	}
	if m.messages != nil {
		fields = append(fields, transaction.FieldMessages)
	}
	if m.response != nil {
		fields = append(fields, transaction.FieldResponse)
	}
	if m.created_at != nil {
		fields = append(fields, transaction.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TransactionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case transaction.FieldIndex:
		return m.Index()
	case transaction.FieldHash:
		return m.Hash()
	case transaction.FieldSuccess:
		return m.Success()
	case transaction.FieldBlockHeight:
		return m.BlockHeight()
	case transaction.FieldGasWanted:
		return m.GasWanted()
	case transaction.FieldGasUsed:
		return m.GasUsed()
	case transaction.FieldMemo:
		return m.Memo()
	case transaction.FieldGasFee:
		return m.GasFee()
	case transaction.FieldMessages:
		return m.Messages()
	case transaction.FieldResponse:
		return m.Response()
	case transaction.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TransactionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case transaction.FieldIndex:
		return m.OldIndex(ctx)
	case transaction.FieldHash:
		return m.OldHash(ctx)
	case transaction.FieldSuccess:
		return m.OldSuccess(ctx)
	case transaction.FieldBlockHeight:
		return m.OldBlockHeight(ctx)
	case transaction.FieldGasWanted:
		return m.OldGasWanted(ctx)
	case transaction.FieldGasUsed:
		return m.OldGasUsed(ctx)
	case transaction.FieldMemo:
		return m.OldMemo(ctx)
	case transaction.FieldGasFee:
		return m.OldGasFee(ctx)
	case transaction.FieldMessages:
		return m.OldMessages(ctx)
	case transaction.FieldResponse:
		return m.OldResponse(ctx)
	case transaction.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Transaction field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TransactionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case transaction.FieldIndex:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIndex(v)
		return nil
	case transaction.FieldHash:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHash(v)
		return nil
	case transaction.FieldSuccess:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSuccess(v)
		return nil
	case transaction.FieldBlockHeight:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBlockHeight(v)
		return nil
	case transaction.FieldGasWanted:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGasWanted(v)
		return nil
	case transaction.FieldGasUsed:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGasUsed(v)
		return nil
	case transaction.FieldMemo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMemo(v)
		return nil
	case transaction.FieldGasFee:
		v, ok := value.(schema.GasFee)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGasFee(v)
		return nil
	case transaction.FieldMessages:
		v, ok := value.([]schema.Message)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMessages(v)
		return nil
	case transaction.FieldResponse:
		v, ok := value.(schema.Response)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponse(v)
		return nil
	case transaction.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Transaction field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TransactionMutation) AddedFields() []string {
	var fields []string
	if m.addindex != nil {
		fields = append(fields, transaction.FieldIndex)
	}
	if m.addblock_height != nil {
		fields = append(fields, transaction.FieldBlockHeight)
	}
	if m.addgas_wanted != nil {
		fields = append(fields, transaction.FieldGasWanted)
	}
	if m.addgas_used != nil {
		fields = append(fields, transaction.FieldGasUsed)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TransactionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case transaction.FieldIndex:
		return m.AddedIndex()
	case transaction.FieldBlockHeight:
		return m.AddedBlockHeight()
	case transaction.FieldGasWanted:
		return m.AddedGasWanted()
	case transaction.FieldGasUsed:
		return m.AddedGasUsed()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TransactionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case transaction.FieldIndex:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIndex(v)
		return nil
	case transaction.FieldBlockHeight:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddBlockHeight(v)
		return nil
	case transaction.FieldGasWanted:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGasWanted(v)
		return nil
	case transaction.FieldGasUsed:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGasUsed(v)
		return nil
	}
	return fmt.Errorf("unknown Transaction numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TransactionMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(transaction.FieldMemo) {
		fields = append(fields, transaction.FieldMemo)
	}
	if m.FieldCleared(transaction.FieldGasFee) {
		fields = append(fields, transaction.FieldGasFee)
	}
	if m.FieldCleared(transaction.FieldMessages) {
		fields = append(fields, transaction.FieldMessages)
	}
	if m.FieldCleared(transaction.FieldResponse) {
		fields = append(fields, transaction.FieldResponse)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TransactionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TransactionMutation) ClearField(name string) error {
	switch name {
	case transaction.FieldMemo:
		m.ClearMemo()
		return nil
	case transaction.FieldGasFee:
		m.ClearGasFee()
		return nil
	case transaction.FieldMessages:
		m.ClearMessages()
		return nil
	case transaction.FieldResponse:
		m.ClearResponse()
		return nil
	}
	return fmt.Errorf("unknown Transaction nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TransactionMutation) ResetField(name string) error {
	switch name {
	case transaction.FieldIndex:
		m.ResetIndex()
		return nil
	case transaction.FieldHash:
		m.ResetHash()
		return nil
	case transaction.FieldSuccess:
		m.ResetSuccess()
		return nil
	case transaction.FieldBlockHeight:
		m.ResetBlockHeight()
		return nil
	case transaction.FieldGasWanted:
		m.ResetGasWanted()
		return nil
	case transaction.FieldGasUsed:
		m.ResetGasUsed()
		return nil
	case transaction.FieldMemo:
		m.ResetMemo()
		return nil
	case transaction.FieldGasFee:
		m.ResetGasFee()
		return nil
	case transaction.FieldMessages:
		m.ResetMessages()
		return nil
	case transaction.FieldResponse:
		m.ResetResponse()
		return nil
	case transaction.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Transaction field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TransactionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TransactionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TransactionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TransactionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TransactionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TransactionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TransactionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Transaction unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TransactionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Transaction edge %s", name)
}
