// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gno.land-block-indexer/ent/predicate"
	"gno.land-block-indexer/ent/restorehistory"
)

// RestoreHistoryDelete is the builder for deleting a RestoreHistory entity.
type RestoreHistoryDelete struct {
	config
	hooks    []Hook
	mutation *RestoreHistoryMutation
}

// Where appends a list predicates to the RestoreHistoryDelete builder.
func (_d *RestoreHistoryDelete) Where(ps ...predicate.RestoreHistory) *RestoreHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RestoreHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RestoreHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RestoreHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(restorehistory.Table, sqlgraph.NewFieldSpec(restorehistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RestoreHistoryDeleteOne is the builder for deleting a single RestoreHistory entity.
type RestoreHistoryDeleteOne struct {
	_d *RestoreHistoryDelete
}

// Where appends a list predicates to the RestoreHistoryDelete builder.
func (_d *RestoreHistoryDeleteOne) Where(ps ...predicate.RestoreHistory) *RestoreHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RestoreHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{restorehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RestoreHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
