// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gno.land-block-indexer/ent/restorehistory"
)

// RestoreHistory is the model entity for the RestoreHistory schema.
type RestoreHistory struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier for the restore history entry
	ID int `json:"id,omitempty"`
	// Start of the block restore range
	RestoreRangeStart int `json:"restore_range_start,omitempty"`
	// End of the block restore range
	RestoreRangeEnd int `json:"restore_range_end,omitempty"`
	// Block currently being restored
	BeingBlock   int `json:"being_block,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RestoreHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case restorehistory.FieldID, restorehistory.FieldRestoreRangeStart, restorehistory.FieldRestoreRangeEnd, restorehistory.FieldBeingBlock:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RestoreHistory fields.
func (_m *RestoreHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case restorehistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case restorehistory.FieldRestoreRangeStart:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field restore_range_start", values[i])
			} else if value.Valid {
				_m.RestoreRangeStart = int(value.Int64)
			}
		case restorehistory.FieldRestoreRangeEnd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field restore_range_end", values[i])
			} else if value.Valid {
				_m.RestoreRangeEnd = int(value.Int64)
			}
		case restorehistory.FieldBeingBlock:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field being_block", values[i])
			} else if value.Valid {
				_m.BeingBlock = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RestoreHistory.
// This includes values selected through modifiers, order, etc.
func (_m *RestoreHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RestoreHistory.
// Note that you need to call RestoreHistory.Unwrap() before calling this method if this RestoreHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RestoreHistory) Update() *RestoreHistoryUpdateOne {
	return NewRestoreHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RestoreHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RestoreHistory) Unwrap() *RestoreHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RestoreHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RestoreHistory) String() string {
	var builder strings.Builder
	builder.WriteString("RestoreHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("restore_range_start=")
	builder.WriteString(fmt.Sprintf("%v", _m.RestoreRangeStart))
	builder.WriteString(", ")
	builder.WriteString("restore_range_end=")
	builder.WriteString(fmt.Sprintf("%v", _m.RestoreRangeEnd))
	builder.WriteString(", ")
	builder.WriteString("being_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeingBlock))
	builder.WriteByte(')')
	return builder.String()
}

// RestoreHistories is a parsable slice of RestoreHistory.
type RestoreHistories []*RestoreHistory
