// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"gno.land-block-indexer/ent/account"
	"gno.land-block-indexer/ent/block"
	"gno.land-block-indexer/ent/schema"
	"gno.land-block-indexer/ent/transaction"
	"gno.land-block-indexer/ent/transfer"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescToken is the schema descriptor for token field.
	accountDescToken := accountFields[1].Descriptor()
	// account.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	account.TokenValidator = accountDescToken.Validators[0].(func(string) error)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.IDValidator is a validator for the "id" field. It is called by the builders before save.
	account.IDValidator = accountDescID.Validators[0].(func(string) error)
	blockFields := schema.Block{}.Fields()
	_ = blockFields
	// blockDescHash is the schema descriptor for hash field.
	blockDescHash := blockFields[1].Descriptor()
	// block.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	block.HashValidator = blockDescHash.Validators[0].(func(string) error)
	// blockDescCreatedAt is the schema descriptor for created_at field.
	blockDescCreatedAt := blockFields[5].Descriptor()
	// block.DefaultCreatedAt holds the default value on creation for the created_at field.
	block.DefaultCreatedAt = blockDescCreatedAt.Default.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescHash is the schema descriptor for hash field.
	transactionDescHash := transactionFields[1].Descriptor()
	// transaction.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	transaction.HashValidator = transactionDescHash.Validators[0].(func(string) error)
	// transactionDescSuccess is the schema descriptor for success field.
	transactionDescSuccess := transactionFields[2].Descriptor()
	// transaction.DefaultSuccess holds the default value on creation for the success field.
	transaction.DefaultSuccess = transactionDescSuccess.Default.(bool)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[10].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(time.Time)
	transferFields := schema.Transfer{}.Fields()
	_ = transferFields
	// transferDescFromAddress is the schema descriptor for from_address field.
	transferDescFromAddress := transferFields[1].Descriptor()
	// transfer.FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	transfer.FromAddressValidator = transferDescFromAddress.Validators[0].(func(string) error)
	// transferDescToAddress is the schema descriptor for to_address field.
	transferDescToAddress := transferFields[2].Descriptor()
	// transfer.ToAddressValidator is a validator for the "to_address" field. It is called by the builders before save.
	transfer.ToAddressValidator = transferDescToAddress.Validators[0].(func(string) error)
	// transferDescToken is the schema descriptor for token field.
	transferDescToken := transferFields[3].Descriptor()
	// transfer.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	transfer.TokenValidator = transferDescToken.Validators[0].(func(string) error)
	// transferDescAmount is the schema descriptor for amount field.
	transferDescAmount := transferFields[4].Descriptor()
	// transfer.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	transfer.AmountValidator = transferDescAmount.Validators[0].(func(float64) error)
	// transferDescDenom is the schema descriptor for denom field.
	transferDescDenom := transferFields[5].Descriptor()
	// transfer.DenomValidator is a validator for the "denom" field. It is called by the builders before save.
	transfer.DenomValidator = transferDescDenom.Validators[0].(func(string) error)
	// transferDescCreatedAt is the schema descriptor for created_at field.
	transferDescCreatedAt := transferFields[6].Descriptor()
	// transfer.DefaultCreatedAt holds the default value on creation for the created_at field.
	transfer.DefaultCreatedAt = transferDescCreatedAt.Default.(func() time.Time)
}
